"""The TaskList aggregate root: the container a task always belongs to.

`owner_id` lives on the entity because ownership is what the visibility rule of
ADR-008 is keyed on - a list the caller cannot see answers 404, a list they can
see but may not change answers 403 - but the entity itself makes neither call.
It cannot: deciding between the two requires knowing who is asking, which is a
use-case concern.

The rejected alternative is enforcing per-owner name uniqueness here. An entity
cannot see its siblings, so the check would either be a lie or would need a
repository handed into the domain. Uniqueness is therefore a use-case pre-check
plus a unique index on `(owner_id, lower(name))` (LIST-06, Phases 3 and 4), and
it raises `DuplicateTaskListNameError` there rather than `ValidationError` here:
a collision is a conflict with other state, not a malformed input.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import ClassVar
from uuid import UUID

from taskmanager.domain.validation import optional_text, require_text, require_utc


@dataclass(slots=True)
class TaskList:
    """A named collection of tasks belonging to exactly one owner.

    Only `rename` exists as a mutator. Phase 4 adds the ones its PATCH endpoint
    needs, following the same `now` keyword convention.
    """

    # FEATURES section 8 rule 1: a list name is 1-120 characters trimmed.
    NAME_MAX_LENGTH: ClassVar[int] = 120
    # Same cap as a task description, for the same reason: bounded text never
    # reaches the database or a log line unbounded.
    DESCRIPTION_MAX_LENGTH: ClassVar[int] = 2000

    id: UUID
    owner_id: UUID
    name: str
    created_at: datetime
    updated_at: datetime
    description: str | None = None

    def __post_init__(self) -> None:
        """Normalise and validate every field, however the list was built."""
        self.name = require_text(
            self.name, field="name", max_length=self.NAME_MAX_LENGTH
        )
        self.description = optional_text(
            self.description,
            field="description",
            max_length=self.DESCRIPTION_MAX_LENGTH,
        )
        self.created_at = require_utc(self.created_at, field="created_at")
        self.updated_at = require_utc(self.updated_at, field="updated_at")

    @classmethod
    def create(
        cls,
        *,
        task_list_id: UUID,
        owner_id: UUID,
        name: str,
        description: str | None = None,
        now: datetime,
    ) -> "TaskList":
        """Build a list stamped with the supplied moment.

        The identifier is an argument for the reason given in `task.py`: ids are
        generated by the application layer with uuid4(), never by the entity and
        never by the database (D-11/D-12).
        """
        return cls(
            id=task_list_id,
            owner_id=owner_id,
            name=name,
            created_at=now,
            updated_at=now,
            description=description,
        )

    def rename(self, name: str, *, now: datetime) -> None:
        """Replace the name, applying the same guard construction applied."""
        self.name = require_text(name, field="name", max_length=self.NAME_MAX_LENGTH)
        self.updated_at = require_utc(now, field="now")
