"""The TaskList aggregate root: the container a task always belongs to.

`owner_id` lives on the entity because ownership is what the visibility rule of
ADR-008 is keyed on - a list the caller cannot see answers 404, a list they can
see but may not change answers 403 - but the entity itself makes neither call.
It cannot: deciding between the two requires knowing who is asking, which is a
use-case concern.

The rejected alternative is enforcing per-owner name uniqueness here. An entity
cannot see its siblings, so the check would either be a lie or would need a
repository handed into the domain. Uniqueness is therefore a use-case pre-check
plus a unique index on `(owner_id, name)` (LIST-06, Phases 3 and 4), and it
raises `DuplicateTaskListNameError` there rather than `ValidationError` here:
a collision is a conflict with other state, not a malformed input.

That index is case-sensitive, unlike the one over `lower(email)` on users,
because this entity performs no case folding on `name`: `Alpha` and `alpha` are
two names it considers distinct, and an index that disagreed would refuse a list
the domain accepts (D-12).
"""

from dataclasses import dataclass
from datetime import datetime
from typing import ClassVar
from uuid import UUID

from taskmanager.domain.validation import optional_text, require_text, require_utc


@dataclass(slots=True)
class TaskList:
    """A named collection of tasks belonging to exactly one owner.

    `rename` and `describe` are the mutators, one per field the PATCH endpoint
    may change, both following the same `now` keyword convention. `owner_id`,
    `id` and `created_at` have none on purpose: a list does not change hands and
    does not get re-created.
    """

    # FEATURES section 8 rule 1: a list name is 1-120 characters trimmed.
    NAME_MAX_LENGTH: ClassVar[int] = 120
    # Same cap as a task description, for the same reason: bounded text never
    # reaches the database or a log line unbounded.
    DESCRIPTION_MAX_LENGTH: ClassVar[int] = 2000

    id: UUID
    owner_id: UUID
    name: str
    created_at: datetime
    updated_at: datetime
    description: str | None = None

    def __post_init__(self) -> None:
        """Normalise and validate every field, however the list was built."""
        self.name = self.normalised_name(self.name)
        self.description = optional_text(
            self.description,
            field="description",
            max_length=self.DESCRIPTION_MAX_LENGTH,
        )
        self.created_at = require_utc(self.created_at, field="created_at")
        self.updated_at = require_utc(self.updated_at, field="updated_at")

    @classmethod
    def normalised_name(cls, name: str) -> str:
        """The name as this entity would store it, or the refusal it would raise.

        The one normaliser, called by `__post_init__` and `rename` and offered to
        the use cases that must *compare* names before anything is assigned
        (Phase 4 review WR-01). LIST-06's pre-check asked the repository about
        the raw client string while the repository and this entity both trimmed
        it, so `" Alpha "` re-sent to a list named `Alpha` was compared as a
        different name, matched the list's own row, and was refused with a false
        409. A use case that needs "the name this would become" asks here rather
        than calling `strip()` itself, which would be a second copy of the rule.
        """
        return require_text(name, field="name", max_length=cls.NAME_MAX_LENGTH)

    @classmethod
    def create(
        cls,
        *,
        task_list_id: UUID,
        owner_id: UUID,
        name: str,
        description: str | None = None,
        now: datetime,
    ) -> "TaskList":
        """Build a list stamped with the supplied moment.

        The identifier is an argument for the reason given in `task.py`: ids are
        generated by the application layer with uuid4(), never by the entity and
        never by the database (D-11/D-12).
        """
        return cls(
            id=task_list_id,
            owner_id=owner_id,
            name=name,
            created_at=now,
            updated_at=now,
            description=description,
        )

    def rename(self, name: str, *, now: datetime) -> None:
        """Replace the name, applying the same guard construction applied."""
        # Validate everything before assigning anything, for the reason spelled
        # out in `Task.rename`: a refused call must leave the aggregate exactly
        # as it found it.
        moment = require_utc(now, field="now")
        self.name = self.normalised_name(name)
        self.updated_at = moment

    def describe(self, description: str | None, *, now: datetime) -> None:
        """Replace or clear the description, under the constructor's own guard."""
        # Same three rules as `rename`: validate before assigning, `now` is
        # keyword-only, and `updated_at` takes the validated moment. The call
        # delegates to `optional_text`, which folds "" to None - so an explicit
        # empty string clears the field exactly as an explicit JSON null does,
        # and the absence keeps the single representation `__post_init__`
        # already guarantees (Phase 4 D-05).
        moment = require_utc(now, field="now")
        self.description = optional_text(
            description,
            field="description",
            max_length=self.DESCRIPTION_MAX_LENGTH,
        )
        self.updated_at = moment
