"""Roadmap SC-3: the migration builds the schema, and can take it apart again.

These five tests are what turns "there is an Alembic directory" into a claim
worth reading. One asserts the tables the baseline actually produced, one asserts
the ORM models and the revision history still agree, one proves `downgrade base`
is a working path rather than a stub, one walks the revision chain, and one
reverses the newest revision a single step and puts it back.

What they cannot prove is DB-04. Alembic autogenerate does not compare `CHECK`
constraints at all, so a revision that dropped one would be reported as no drift;
`test_constraints.py` is where those are proven, by inserts PostgreSQL refuses.
"""

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect
from sqlalchemy.pool import NullPool

from taskmanager.infrastructure.db.constraints import IX_TASKS_ASSIGNEE_ID
from tests.integration.conftest import ROOT, alembic_config

pytestmark = pytest.mark.integration

# The three domain tables plus the bookkeeping table Alembic maintains itself.
EXPECTED_TABLES = {"users", "task_lists", "tasks", "alembic_version"}
DOMAIN_TABLES = frozenset({"users", "task_lists", "tasks"})

VERSIONS = ROOT / "migrations" / "versions"

EXPECTED_REVISIONS = frozenset({"0001", "0002"})

# `ScriptDirectory` only reads the version files; it never opens a connection.
# A DSN is still required to build the `Config`, so this one is deliberately
# unusable - if a future edit made that test touch the database, it would fail
# loudly here rather than quietly connect to whatever the environment points at.
DSN_PLACEHOLDER = "postgresql+psycopg://reads-no-database/"


def test_alembic_upgrade_creates_every_table(
    migrated_database: None, database_url: str
) -> None:
    """The schema this suite runs against is the one the baseline produced."""
    engine = create_engine(database_url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            tables = set(inspect(connection).get_table_names())
    finally:
        engine.dispose()

    # Equality, not a containment check: a leftover table from an abandoned
    # revision is exactly the stale state the fixture's downgrade-first step
    # exists to remove, so it must be reported rather than tolerated.
    assert tables == EXPECTED_TABLES


def test_the_models_and_the_migrations_do_not_disagree(
    migrated_database: None, database_url: str
) -> None:
    """D-02: if this fails, a model changed and no revision was written.

    `command.check` compares the live schema against `Base.metadata` exactly as
    autogenerate would, and raises when it finds a difference. The failure is
    re-reported without a traceback because the drift summary Alembic carries in
    the exception is the whole message - the stack it was raised from says
    nothing a reader needs.
    """
    try:
        command.check(alembic_config(database_url))
    except AutogenerateDiffsDetected as drift:
        pytest.fail(
            f"The ORM models drifted from the migration history: {drift}\n"
            "Write a revision for the model change, or revert it.",
            pytrace=False,
        )


def test_downgrade_base_removes_every_table(
    migrated_database: None, database_url: str
) -> None:
    """D-10's downgrade is real, and proving it does not cost the session.

    The downgrade runs on a connection this test opened and begins a transaction
    on; the assertion is made inside that transaction, and then it is rolled back.
    PostgreSQL's DDL is transactional, so the three tables come back with it and
    every later test in the session still finds the schema it needs. Committing
    the downgrade here - or letting Alembic open its own connection, which would
    commit - would leave the database empty and break everything that runs after.
    """
    config = alembic_config(database_url)
    engine = create_engine(database_url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            transaction = connection.begin()
            try:
                config.attributes["connection"] = connection
                command.downgrade(config, "base")

                remaining = set(inspect(connection).get_table_names())
                assert remaining & DOMAIN_TABLES == set()
            finally:
                transaction.rollback()
    finally:
        engine.dispose()


def test_revision_0002_reverses_and_reapplies_one_step(
    migrated_database: None, database_url: str
) -> None:
    """The single-step reversal `downgrade base` cannot stand in for.

    `migrated_database` already runs `downgrade base` then `upgrade head` once
    per session, which proves the chain works from an empty database. It says
    nothing about reversing the *newest* revision on its own - and that is the
    operation a developer or an evaluator actually performs when a deploy has
    to be rolled back. A `0002.downgrade()` that dropped the wrong object, or
    dropped the column before the index, would go unnoticed until then.

    Both directions are asserted against the *reflected* schema rather than
    against the revision file: what matters is what the server holds, not what
    the migration meant to do. The whole thing runs inside one transaction that
    is rolled back, for the reason `test_downgrade_base_removes_every_table`
    gives - PostgreSQL's DDL is transactional, so the session's schema survives.
    """
    config = alembic_config(database_url)
    engine = create_engine(database_url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            transaction = connection.begin()
            try:
                config.attributes["connection"] = connection

                command.downgrade(config, "0001")
                inspector = inspect(connection)
                columns = {column["name"] for column in inspector.get_columns("users")}
                indexes = {index["name"] for index in inspector.get_indexes("tasks")}
                assert "full_name" not in columns
                assert IX_TASKS_ASSIGNEE_ID not in indexes

                command.upgrade(config, "head")
                inspector = inspect(connection)
                columns = {column["name"] for column in inspector.get_columns("users")}
                indexes = {index["name"] for index in inspector.get_indexes("tasks")}
                assert "full_name" in columns
                assert IX_TASKS_ASSIGNEE_ID in indexes
            finally:
                transaction.rollback()
    finally:
        engine.dispose()


def test_the_revisions_form_one_unbroken_chain_ending_at_the_head() -> None:
    """The history is `0001 -> 0002`, with `head` resolving to `0002`.

    This replaces `test_the_migration_directory_holds_exactly_one_revision`,
    retired here rather than deleted quietly. That test asserted a *count*, and
    the count became false the moment AUTH-01 needed `users.full_name` - which
    is the genuine change `0001`'s docstring said a second revision would wait
    for. The chain is the stronger property anyway: a count says nothing about
    whether the revisions can actually be walked, and a second file with a wrong
    `down_revision`, a duplicate identifier or a second head would satisfy it
    while making `upgrade head` fail or silently skip a revision.

    Read through Alembic's own `ScriptDirectory` rather than off the filesystem,
    so what is asserted is the graph Alembic will walk, not the names of some
    files in a folder.
    """
    scripts = ScriptDirectory.from_config(alembic_config(DSN_PLACEHOLDER))
    revisions = {script.revision: script for script in scripts.walk_revisions()}

    # Vacuity guard: a renamed directory or a wrong hop count in `ROOT` would
    # otherwise leave every assertion below quantifying over nothing.
    assert set(revisions) == EXPECTED_REVISIONS

    assert revisions["0001"].down_revision is None
    assert revisions["0002"].down_revision == "0001"
    assert scripts.get_current_head() == "0002"
