"""Roadmap SC-3: the migration builds the schema, and can take it apart again.

These four tests are what turns "there is an Alembic directory" into a claim
worth reading. One asserts the tables the baseline actually produced, one asserts
the ORM models and the revision history still agree, one proves `downgrade base`
is a working path rather than a stub, and one guards against the whole set
becoming vacuous.

What they cannot prove is DB-04. Alembic autogenerate does not compare `CHECK`
constraints at all, so a revision that dropped one would be reported as no drift;
`test_constraints.py` is where those are proven, by inserts PostgreSQL refuses.
"""

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect
from sqlalchemy.pool import NullPool

from tests.integration.conftest import ROOT, alembic_config

pytestmark = pytest.mark.integration

# The three domain tables plus the bookkeeping table Alembic maintains itself.
EXPECTED_TABLES = {"users", "task_lists", "tasks", "alembic_version"}
DOMAIN_TABLES = frozenset({"users", "task_lists", "tasks"})

VERSIONS = ROOT / "migrations" / "versions"

EXPECTED_REVISIONS = 1


def test_alembic_upgrade_creates_every_table(
    migrated_database: None, database_url: str
) -> None:
    """The schema this suite runs against is the one the baseline produced."""
    engine = create_engine(database_url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            tables = set(inspect(connection).get_table_names())
    finally:
        engine.dispose()

    # Equality, not a containment check: a leftover table from an abandoned
    # revision is exactly the stale state the fixture's downgrade-first step
    # exists to remove, so it must be reported rather than tolerated.
    assert tables == EXPECTED_TABLES


def test_the_models_and_the_migrations_do_not_disagree(
    migrated_database: None, database_url: str
) -> None:
    """D-02: if this fails, a model changed and no revision was written.

    `command.check` compares the live schema against `Base.metadata` exactly as
    autogenerate would, and raises when it finds a difference. The failure is
    re-reported without a traceback because the drift summary Alembic carries in
    the exception is the whole message - the stack it was raised from says
    nothing a reader needs.
    """
    try:
        command.check(alembic_config(database_url))
    except AutogenerateDiffsDetected as drift:
        pytest.fail(
            f"The ORM models drifted from the migration history: {drift}\n"
            "Write a revision for the model change, or revert it.",
            pytrace=False,
        )


def test_downgrade_base_removes_every_table(
    migrated_database: None, database_url: str
) -> None:
    """D-10's downgrade is real, and proving it does not cost the session.

    The downgrade runs on a connection this test opened and begins a transaction
    on; the assertion is made inside that transaction, and then it is rolled back.
    PostgreSQL's DDL is transactional, so the three tables come back with it and
    every later test in the session still finds the schema it needs. Committing
    the downgrade here - or letting Alembic open its own connection, which would
    commit - would leave the database empty and break everything that runs after.
    """
    config = alembic_config(database_url)
    engine = create_engine(database_url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            transaction = connection.begin()
            try:
                config.attributes["connection"] = connection
                command.downgrade(config, "base")

                remaining = set(inspect(connection).get_table_names())
                assert remaining & DOMAIN_TABLES == set()
            finally:
                transaction.rollback()
    finally:
        engine.dispose()


def test_the_migration_directory_holds_exactly_one_revision() -> None:
    """D-10: one baseline, and no fake second revision to demonstrate versioning.

    The non-empty half is the vacuity guard - a renamed directory or a wrong hop
    count in `ROOT` would otherwise leave this test asserting that an empty list
    has a length it does not have, and the schema tests above reading a database
    nothing migrated. The exact count is the decision: a second revision appears
    when a genuine change requires one, never as an artifact produced to show the
    tool works.
    """
    revisions = sorted(path.name for path in VERSIONS.glob("*.py"))

    assert revisions
    assert len(revisions) == EXPECTED_REVISIONS, revisions
