"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-09-18 15:49:44.622346

The complete Phase 3 schema in one revision: users, task_lists and tasks, with
the D-12 constraint names, the D-11 column types and a downgrade that really
removes all three tables.

Two columns are here as a corrected reading of D-10, which lists `users` without
`updated_at` and `task_lists` without `description`. Both fields exist on the
domain entities (`user.py`, `task_list.py`), and a mapper cannot round-trip a
field that has no column, so shipping D-10 literally would have meant a second
revision invented later purely to patch the first one. The correction is made
here instead.

A second revision will appear only when a genuine change requires one. Never a
fake one to demonstrate that versioning works - an evaluator can read
`alembic history`, and an empty `pass` migration would tell them less than this
sentence does.

Autogenerated against an empty `taskmanager_test`, then hand-edited for the
revision identifier, this docstring and the comments below. The constraint names
are left as literals rather than imported from
`taskmanager.infrastructure.db.constraints`: a revision is a frozen record of
what a database was migrated to, and a name read from a constant would silently
rewrite that record the day the constant is renamed. The agreement is checked
mechanically anyway, in two hops - `tests/unit/infrastructure/test_models.py`
asserts the constants against the DDL the models render, and `alembic check`
asserts this schema against those same models.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create users, task_lists and tasks."""
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    # Case-INSENSITIVE email uniqueness, and the deliberate opposite of
    # uq_task_lists_owner_id_name below. `User` lowercases its address on
    # construction, so this index only defends a rule the entity already
    # enforces; `TaskList` folds no case, so the same trick on `name` would
    # refuse two values the domain considers distinct (D-12).
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "task_lists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        # ON DELETE CASCADE is DB-05, enforced by PostgreSQL rather than by
        # application code walking the children.
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_task_lists_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_lists")),
        # Plain UNIQUE (owner_id, name): the race-proof backstop behind
        # LIST-06's 409, which the use-case pre-check cannot provide on its own.
        sa.UniqueConstraint(
            "owner_id", "name", name=op.f("uq_task_lists_owner_id_name")
        ),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_list_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        # The three CHECK constraints of DB-04 and D-12. They are present
        # because autogenerate renders every constraint of a table it is adding
        # for the first time - but `alembic check` can never prove they are
        # still here afterwards: SQLAlchemy does not reflect CHECK constraints
        # into a comparable form, so a later revision dropping one would be
        # reported as no drift at all. The insert-and-refuse integration tests
        # are the only real proof, and DB-04 rests on them, not on this file.
        sa.CheckConstraint(
            "(status = 'completed') = (completed_at IS NOT NULL)",
            name=op.f("ck_tasks_completed_at_matches_status"),
        ),
        sa.CheckConstraint(
            "priority IN ('low','medium','high')", name=op.f("ck_tasks_priority")
        ),
        sa.CheckConstraint(
            "status IN ('pending','in_progress','completed')",
            name=op.f("ck_tasks_status"),
        ),
        # SET NULL, not CASCADE: deleting a user must not delete the tasks they
        # happened to be assigned, only un-assign them (D-12).
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tasks_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_list_id"],
            ["task_lists.id"],
            name=op.f("fk_tasks_task_list_id_task_lists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(
        op.f("ix_tasks_task_list_id"), "tasks", ["task_list_id"], unique=False
    )


def downgrade() -> None:
    """Drop everything upgrade() created, children before parents."""
    # Reverse dependency order: tasks references task_lists and users, and
    # task_lists references users, so dropping users first would fail on the
    # foreign keys. The two indexes are dropped explicitly because both were
    # created as standalone statements rather than inside a CREATE TABLE.
    op.drop_index(op.f("ix_tasks_task_list_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("task_lists")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
