"""full_name and the assignee index

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 15:20:11.104553

The genuine change `0001`'s docstring said would have to arrive before a second
revision did. AUTH-01 and ASGN-03 both need a display name - registration
collects one, and the user directory the assignment UI reads is a list of names,
not of email addresses - so `users` gains `full_name`.

`full_name` is `NOT NULL` and this runs against databases that already hold
rows: every Phase 4 developer volume carries the demo-seed account, and the
evaluator's `taskmanager` database will too by the time they upgrade. A bare
`NOT NULL` add would be refused there. The column is therefore added with a
transient `server_default`, and the very next statement drops it - `models.py`
declares no server-side default on any column (the `Clock` port is the only
source of a value the ORM did not write), so a surviving default would be
permanent `alembic check` drift rather than a harmless leftover.

The constraint and index names are literals here, not imports from
`taskmanager.infrastructure.db.constraints`, for the reason `0001` gives at
length (ADR-025): a revision is a frozen record of what a database was migrated
to, and a name read from a constant would silently rewrite that record the day
the constant is renamed. `op.f(...)` marks the names the naming convention
generates, so Alembic does not re-apply the convention to them.

Hand-written rather than autogenerated, then checked the same way `0001` is: in
two hops, `tests/unit/infrastructure/test_models.py` against the DDL the models
render, and `alembic check` against this chain.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add users.full_name over existing rows."""
    # The server_default is what lets a NOT NULL column arrive in a populated
    # table: PostgreSQL uses it to fill the rows that are already there. It is
    # dropped in the statement below, in the same upgrade, because no column in
    # `models.py` declares one and `alembic check` compares the two.
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.String(length=100),
            nullable=False,
            server_default="Unnamed",
        ),
    )
    op.alter_column("users", "full_name", server_default=None)


def downgrade() -> None:
    """Drop users.full_name."""
    op.drop_column("users", "full_name")
